feat: software-update replace filenames

diff --git a/.github/workflows/terraform_ansible_software_availability.yml b/.github/workflows/terraform_ansible_software_availability.yml
--- a/.github/workflows/terraform_ansible_software_availability.yml
+++ b/.github/workflows/terraform_ansible_software_availability.yml
@@ -27,21 +27,23 @@ jobs:
         terraform_module_ansible: [ansible_sap_ecc_hana_system_copy_hdb,ansible_sap_hana_install,ansible_sap_s4hana_install_maintplan,ansible_sap_s4hana_system_copy_hdb]
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3.0.2
+        with:
+          path: gh_repo
       - name: Ansible setup
         id: local_setup
         run: |
           python --version
           python -m pip install ansible-core requests beautifulsoup4 lxml
           ansible --version
-          ansible-galaxy collection install git+https://github.com/sap-linuxlab/community.sap_launchpad.git,main
+          ansible-galaxy collection install git+https://github.com/sap-linuxlab/community.sap_launchpad.git,main -p ./ansible_collections
       - name: Terraform Module for Ansible - check software
         id: identify_software_list
         env:
           sap_user_id: ${{ secrets.SAP_USER_ID }}
           sap_user_id_password: ${{ secrets.SAP_USER_ID_PASSWORD }}
         run: |
-          cd "./all/${{ matrix.terraform_module_ansible }}"
+          cd "./gh_repo/all/${{ matrix.terraform_module_ansible }}"
           # Extract from softwarecenter_search_list_.* until first empty line, then remove yaml formatting and sort for unique
           export software_list=$(cat create_ansible_extravars.tf | awk '!NF{f=0} /^.*softwarecenter_search_list.*/{f=1} f{print}' | awk '!/.*softwarecenter_search_list.*/' | awk '{sub(/#.*/,""); print}' | awk '{sub(/ .*- '\''/,""); print}' | tr -d "'" | sort | uniq)
           export errors_list=""
@@ -57,13 +59,67 @@ jobs:
                 continue
             fi
           done
+          cd ../../../
           if [ -z "$errors_list" ]
           then
             exit 0
           else
-            echo "### ERRORS indentified ####"
-            echo "Terraform Templates for SAP require updating,"
+            echo "### ERRORS identified ####"
+            echo "Terraform Modules for SAP require updating,"
             echo "as the following SAP Software are no longer available:"
             echo "$errors_list" | tr " " "\n"
-            exit 1
+            cd ./ansible_collections/community/sap_launchpad/plugins
+            touch python_module_fuzzy_call_script.py
+            echo '#!/usr/bin/env python3' >> python_module_fuzzy_call_script.py
+            echo 'import sys' >> python_module_fuzzy_call_script.py
+            echo 'search_file=sys.argv[1]' >> python_module_fuzzy_call_script.py
+            echo 'from module_utils.sap_launchpad_software_center_download_search_fuzzy import *' >> python_module_fuzzy_call_script.py
+            echo "username='$sap_user_id'" >> python_module_fuzzy_call_script.py
+            echo "password='$sap_user_id_password'" >> python_module_fuzzy_call_script.py
+            echo 'sap_sso_login(username, password)' >> python_module_fuzzy_call_script.py
+            echo 'query_result = search_software_fuzzy(search_file)' >> python_module_fuzzy_call_script.py
+            echo 'if len(query_result) >= 2:' >> python_module_fuzzy_call_script.py
+            echo "    if 'IMDB_CLIENT20' in query_result[0]['Title']:" >> python_module_fuzzy_call_script.py
+            echo "        print(query_result[-1]['Title'])" >> python_module_fuzzy_call_script.py
+            echo "    elif '70SWPM' in query_result[0]['Title']:" >> python_module_fuzzy_call_script.py
+            echo "        print(query_result[-1]['Title'])" >> python_module_fuzzy_call_script.py
+            echo "    else:" >> python_module_fuzzy_call_script.py
+            echo '        for item in query_result:' >> python_module_fuzzy_call_script.py
+            echo '            print("ERROR. More than 1 result, manual intervention required.")' >> python_module_fuzzy_call_script.py
+            echo "            print('Identified ' + item['Description'] + ', ' + item['Infotype'] + ': ' + item['Title'])" >> python_module_fuzzy_call_script.py
+            echo 'else:' >> python_module_fuzzy_call_script.py
+            echo "    print(query_result[0]['Title'])" >> python_module_fuzzy_call_script.py
+            export exit1_check=0
+            cd ../../../../
+            for filename in $errors_list
+            do
+              filename_noext="${filename%.*}"
+              filename_id_only="${filename_noext##*-}"
+              cd ./ansible_collections/community/sap_launchpad/plugins
+              search_file=$(python ./python_module_fuzzy_call_script.py $filename_id_only)
+              cd ../../../../
+              if [[ "$search_file" == *"ERROR"* ]]; then
+                echo -e $search_file
+                printf $search_file
+                exit1_check=1
+              else
+                echo "Perform recursive sed for $filename change to $search_file"
+                cd ./gh_repo
+                find . -type f -not -path '*/\.*' -exec sed -i "s/$filename/$search_file/g" {} \;
+                cd ../
+              fi
+            done
+            if $exit1_check == "1"; then
+              exit 1
+            fi
           fi
+      - name: Commit to main branch
+        id: git_commit_auto
+        run: |
+          cd ./gh_repo
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+          git add .
+          git status
+          git commit -m "software-update: replace with new filenames $(date +%F)"
+          git push
